type: rpm-ostree
install:
  - sddm
  - wofi
  - xorg-x11-server-Xwayland
  - wireplumber
  - pipewire
  - polkit
  - network-manager-applet
  - bluez
  - bluez-tools
  - blueman
  - thunar
  - slurp
  - grim
  - lxappearance
  - wlr-randr
  - wlsunset
  - grimshot
  - xdg-user-dirs
  - foot