type: rpm-ostree
install:
# launcher
  - rofi-wayland

# environment
  - xorg-x11-server-Xwayland
  - polkit
  - lxpolkit
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - wl-clipboard
  - gnome-keyring
  - pavucontrol
  - playerctl
  - qt5-qtwayland
  - qt6-qtwayland
  - vulkan-validation-layers
  - vulkan-tools
  - google-noto-emoji-fonts
  - gnome-disk-utility
  
# sound
  - wireplumber
  - pipewire
  - pamixer

# networking
  - network-manager-applet
  - NetworkManager-openvpn
  - NetworkManager-openconnect
  - bluez
  - bluez-tools

# file manager
  - thunar
  - thunar-archive-plugin 
  - thunar-volman
  - xarchiver
  - imv
  - p7zip
  - unrar-free

# screenshot
  - slurp
  - grim

# display
  - wlr-randr
  - wlsunset
  - grimshot
  - brightnessctl
  - swaylock
  - swayidle
  - kanshi

# terminal
  - foot

# notifications
  - dunst

# mpv, since flatpak mpv and celluloid have issues
  - mpv

# theme and GUI
  - adwaita-qt5
  - fontawesome-fonts-all
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme
  - breeze-icon-theme 
  - papirus-icon-theme
remove:
  - dconf
  - ibus
  - ibus-anthy
  - ibus-gtk3
  - ibus-gtk4
  - ibus-hangul
  - ibus-libpinyin
  - ibus-libzhuyin
  - ibus-m17n
  - ibus-typing-booster
