# image will be published to ghcr.io/<user>/<name>
name: wayfire
# description will be included in the image's metadata
description: ublue images for wayland compositors

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-files.yml
  - from-file: common-packages.yml

  - type: files
    files:
      - wayfire/usr: /usr 
                  
  - type: rpm-ostree
    install:
      - wayfire
      - wf-shell
      - wayfire-config-manager
      - wf-config
      - xdg-desktop-portal-wlr
      - xdg-desktop-portal-gtk
      - adw-gtk3-theme 

  - from-file: common-scripts.yml
